const actions = {
    SET_DECK: 'SET_DECK',
    INCREMENT_CARD_FLIPS: 'INCREMENT_CARD_FLIPS',
    ADD_TO_FLIPPED_CARDS: 'ADD_TO_FLIPPED_CARDS',
    CLEAR_FLIPPED_CARDS: 'CLEAR_FLIPPED_CARDS',
    ADD_TO_MATCHED_CARDS: 'ADD_TO_MATCHED_CARDS',
    CLEAR_MATCHED_CARDS: 'CLEAR_MATCHED_CARDS'
}

export default Object.freeze(actions);